name: Docker-Testing

on: [workflow_dispatch]

jobs:
  build-file-writer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build File Writer Container
        run: |
          cd FileWriter
          docker build . --tag file-writer

  build-calculator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Calculator Container
        run: |
          cd Calculator
          docker build . --tag calculator
          
  build-static-webpage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Static Webpage Container
        run: |
          cd StaticWebpage
          docker build . --tag static-webpage
